### ISSUE TITLE
Mapa_Mental_Web_3.0

### ISSUE THREAD

**Issue by JeroRoque** [SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-JeroRoque#1]
[Wed_3.0_Mapa_Mental_Jeronima_Roque.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-web-3-JeroRoque/files/14681737/Wed_3.0_Mapa_Mental_Jeronima_Roque.pdf)

**Comment by Elisahadad** [comment]
Calificación = 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
